version: '3.8'

services:
  grafana:
    image: acrselfimprovement.azurecr.io/grafana:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  loki:
    image: acrselfimprovement.azurecr.io/loki:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

  nginx:
    image: acrselfimprovement.azurecr.io/nginx:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "80:80"
    volumes:
      - nginx-data:/usr/share/nginx/html

  node-exporter:
    image: acrselfimprovement.azurecr.io/node-exporter:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "9100:9100"

  ollama:
    image: acrselfimprovement.azurecr.io/ollama:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "11434:11434"

  open-webui:
    image: acrselfimprovement.azurecr.io/open-webui:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "8080:8080"

  pgadmin:
    image: acrselfimprovement.azurecr.io/pgadmin:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  postgres:
    image: acrselfimprovement.azurecr.io/postgres:5eb1c91ce93c3df345d6181ed8ac6f3ebebffaef
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: acrselfimprovement.azurecr.io/prometheus:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus

  promtail:
    image: acrselfimprovement.azurecr.io/promtail:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    volumes:
      - promtail-data:/promtail

  rabbitmq:
    image: acrselfimprovement.azurecr.io/rabbitmq:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  frontend:
    image: acrselfimprovement.azurecr.io/selfimprovement-frontend:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "3000:3000"

  goal:
    image: acrselfimprovement.azurecr.io/selfimprovement-goal:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "8081:8080"

  identity:
    image: acrselfimprovement.azurecr.io/selfimprovement-identity:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "8082:8080"

  prompt:
    image: acrselfimprovement.azurecr.io/selfimprovement-prompt:4e7c69ae964544f1f86a497cbbfb5be7d4db868a
    ports:
      - "8083:8080"

volumes:
  grafana-data:
  loki-data:
  nginx-data:
  pgadmin-data:
  postgres-data:
  prometheus-data:
  promtail-data:
  rabbitmq-data:
