version: '3.7'

services:
  frontend:
    container_name: selfimprovement-frontend
    build:
      context: ./Source/Web/
      dockerfile: Dockerfile.local
    image: ${ACR_NAME}.azurecr.io/selfimprovement-frontend:${{ github.sha }}
    ports:
      - "3000:3000"
    restart: always

  identity:
    container_name: selfimprovement-identity
    build:
      context: ./Source
      dockerfile: IdentityApi/Dockerfile.local
    image: ${ACR_NAME}.azurecr.io/selfimprovement-identity:${{ github.sha }}
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://localhost:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
    ports:
      - "8080:8080"
    restart: on-failure

  goal:
    container_name: selfimprovement-goal
    build:
      context: ./Source
      dockerfile: GoalApi/Dockerfile.local
    image: ${ACR_NAME}.azurecr.io/selfimprovement-goal:${{ github.sha }}
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://localhost:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
    ports:
      - "8081:8080"
    restart: always

  prompt:
    container_name: selfimprovement-prompt
    build:
      context: ./Source
      dockerfile: PromptApi/Dockerfile.local
    image: ${ACR_NAME}.azurecr.io/selfimprovement-prompt:${{ github.sha }}
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://localhost:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
      - BlobStorageConnectionUrl=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
      - Llama2=host.docker.internal:11434
      - GoalApiServiceUrl=host.docker.internal:8081
      - IdentityApiServiceUrl=host.docker.internal:8080
    ports:
      - "8082:8080"
    restart: always
