version: '3.7'

services:
  coredns:
    container_name: coredns
    build:
      context: ./CoreDNS
      dockerfile: Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/coredns:${IMAGE_TAG}"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: always

  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./Rabbitmq
      dockerfile: Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/rabbitmq:${IMAGE_TAG}"
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management Plugin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/
    dns:
      - "127.0.0.1"

  frontend:
    container_name: selfimprovement-frontend
    build:
      context: ./Source/Web/
      dockerfile: Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-frontend:${IMAGE_TAG}"
    ports:
      - "3000:3000"
    restart: always
    dns:
      - "127.0.0.1"

  identity:
    container_name: selfimprovement-identity
    build:
      context: ./Source
      dockerfile: IdentityApi/Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-identity:${IMAGE_TAG}"
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=${POSTGRES_DB_NAME};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - CorsOrigin=http://frontend-static-dns.polandcentral.azurecontainer.io:3000
      - RabbitMqConnectionUrl=amqp://rabbitmq-static-dns.polandcentral.azurecontainer.io:5672/
    ports:
      - "8080:8080"
    restart: always
    dns:
      - "127.0.0.1"

  goal:
    container_name: selfimprovement-goal
    build:
      context: ./Source
      dockerfile: GoalApi/Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-goal:${IMAGE_TAG}"
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=${POSTGRES_DB_NAME};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - CorsOrigin=http://frontend-static-dns.polandcentral.azurecontainer.io:3000
      - RabbitMqConnectionUrl=amqp://rabbitmq-static-dns.polandcentral.azurecontainer.io:5672/
    ports:
      - "8080:8080"
    restart: always
    dns:
      - "127.0.0.1"

  prompt:
    container_name: selfimproved-prompt
    build:
      context: ./Source
      dockerfile: PromptApi/Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-prompt:${IMAGE_TAG}"
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=${POSTGRES_DB_NAME};User ID=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Include Error Detail=true
      - CorsOrigin=http://frontend-static-dns.polandcentral.azurecontainer.io:3000
      - RabbitMqConnectionUrl=amqp://rabbitmq-static-dns.polandcentral.azurecontainer.io:5672/
      - BlobStorageConnectionUrl=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=https://selfimprovementstorage.blob.core.windows.net/blob
      - Llama2=ollama-static-dns.polandcentral.azurecontainer.io:11434
      - GoalApiServiceUrl=goal-static-dns.polandcentral.azurecontainer.io:8080
      - IdentityApiServiceUrl=identity-static-dns.polandcentral.azurecontainer.io:8080
    ports:
      - "8080:8080"
    restart: always
    dns:
      - "127.0.0.1"

  # Additional services unchanged...

volumes:
  ollama:
  prometheus_data:
  open-webui:
  rabbitmq_data:
