version: '3.7'

services:
  frontend:
    container_name: selfimprovement-frontend
    build:
      context: ./Source/Web/
      dockerfile: Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-frontend:${IMAGE_TAG}"
    ports:
      - "3000:3000"
    restart: always

  identity:
    container_name: selfimprovement-identity
    build:
      context: ./Source
      dockerfile: IdentityApi/Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-identity:${IMAGE_TAG}"
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://0.0.0.0:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
    ports:
      - "8080:8080"
    restart: on-failure

  goal:
    container_name: selfimprovement-goal
    build:
      context: ./Source
      dockerfile: GoalApi/Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-goal:${IMAGE_TAG}"
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://0.0.0.0:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
    ports:
      - "8080:8080"
    restart: always

  prompt:
    container_name: selfimprovement-prompt
    build:
      context: ./Source
      dockerfile: PromptApi/Dockerfile.local
    image: "${ACR_NAME}.azurecr.io/selfimprovement-prompt:${IMAGE_TAG}"
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://0.0.0.0:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
      - BlobStorageConnectionUrl=UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite
      - Llama2=host.docker.internal:11434
      - GoalApiServiceUrl=host.docker.internal:8081
      - IdentityApiServiceUrl=host.docker.internal:8080
    ports:
      - "8080:8080"
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=selfimprovement123
      - POSTGRES_DB=SelfImprovementDb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m
        max-file: "3"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@selfimprovement.ai
      - PGADMIN_DEFAULT_PASSWORD=selfimprovement123
    ports:
      - "5050:80"
    volumes:
      - ./Database/Lib/config.py:/pgadmin4/web/config_local.py

  open-webui:
    container_name: open-webui
    restart: on-failure
    build:
      context: ./Ollama
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data

  ollama:
    container_name: ollama
    tty: true
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: on-failure
    user: "1000"
    volumes:
      - ./Monitoring/Grafana/lib:/var/lib/grafana
    ports:
      - "3000:3000"

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: on-failure
    volumes:
      - ./Monitoring/Loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: on-failure
    volumes:
      - ./Monitoring/Promtail:/etc/promtail
    command: -config.expand-env=true -config.file=/etc/promtail/promtail-config.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.2
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./Monitoring/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://0.0.0.0:80/prometheus/

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: on-failure
    ports:
      - "9100:9100"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.9-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management Plugin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/index.html:/usr/share/nginx/html/index.html
    # env_file:
    #   - .env

volumes:
  postgres:
  ollama:
  prometheus_data:
  open-webui:
  rabbitmq_data: