version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=selfimprovement123
      - POSTGRES_DB=SelfImprovementDb
    ports:
      - 5432:5432
    logging:
      options:
        max-size: 10m
        max-file: "3"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@selfimprovement.ai
      - PGADMIN_DEFAULT_PASSWORD=selfimprovement123
    ports:
      - "5050:80"
    volumes:
      - ./Database/Lib/config.py:/pgadmin4/web/config_local.py

  identity:
    container_name: selfimprovement-identity
    restart: on-failure
    build:
      context: ./Source
      dockerfile: IdentityApi/Dockerfile.local
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://localhost:3000
      - Service=http://localhost:8080
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

  goal:
    container_name: selfimprovement-goal
    build:
      context: ./Source
      dockerfile: GoalApi/Dockerfile.local
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://localhost:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
      - Service=http://localhost:8081
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    restart: always

  prompt:
    container_name: selfimprovement-prompt
    build:
      context: ./Source
      dockerfile: PromptApi/Dockerfile.local
    environment:
      - SelfImprovementDbContext=Host=postgres;Port=5432;Database=SelfImprovementDb;User ID=admin;Password=selfimprovement123;Include Error Detail=true
      - CorsOrigin=http://localhost:3000
      - RabbitMqConnectionUrl=amqp://guest:guest@host.docker.internal:5672/
      - Service=http://localhost:8082
      - Llama2=http://host.docker.internal:11434/api/generate
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    restart: always

  open-webui:
    container_name: open-webui
    restart: on-failure
    build:
      context: ./Ollama
      dockerfile: Dockerfile
    ports:
      - "3001:8080"
    volumes:
      - open-webui:/app/backend/data

  ollama:
    container_name: ollama
    tty: true
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    volumes:
      - azurite_data:/data
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

  mailhog:
    container_name: mailhog
    restart: on-failure
    build:
      context: ./Mail
      dockerfile: Dockerfile
    ports:
      - "1025:1025"
      - "8025:8025"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: on-failure
    user: "1000"
    volumes:
      - ./Monitoring/Grafana/lib:/var/lib/grafana
    ports:
      - "3002:3000"

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: on-failure
    volumes:
      - ./Monitoring/Loki:/etc/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    restart: on-failure
    volumes:
      - ./Monitoring/Promtail:/etc/promtail
    command: -config.expand-env=true -config.file=/etc/promtail/promtail-config.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.51.2
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./Monitoring/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://localhost:80/prometheus/

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: on-failure
    ports:
      - "9100:9100"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.9-management
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management Plugin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    depends_on:
        - postgres
        - pgadmin
        - identity
        - open-webui
        - mailhog
        - grafana
        - rabbitmq
    ports:
      - "80:80"
      #- "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/index.html:/usr/share/nginx/html/index.html
    # env_file:
    #   - .env

volumes:
  azurite_data:
  ollama:
  prometheus_data:
  open-webui:
  rabbitmq_data:
