FROM grafana/grafana:latest

USER grafana

RUN grafana-cli plugins install grafana-piechart-panel \
    && grafana-cli plugins install grafana-clock-panel \
    && grafana-cli plugins install grafana-simple-json-datasource

EXPOSE 3000

CMD ["grafana-server", "--homepath=/usr/share/grafana", "--config=/etc/grafana/grafana.ini"]