# Use the official Grafana image from the Docker Hub
FROM grafana/grafana:latest

# Expose port 3000 (default Grafana port)
EXPOSE 3000

# Start Grafana
CMD ["grafana-server", "--homepath=/usr/share/grafana"]
