global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter-static-dns.polandcentral.azurecontainer.io:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana-static-dns.polandcentral.azurecontainer.io:3000']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki-static-dns.polandcentral.azurecontainer.io:3100']
