FROM prom/node-exporter:latest
EXPOSE 9100
ENTRYPOINT ["/bin/node_exporter"]
CMD ["--path.procfs=/host/proc", "--path.sysfs=/host/sys", "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)"]
