name: 🐘 Create Postgres Database

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create PostgreSQL Server
        run: |
          az postgres server create \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --name selfimprovementaipsql \
            --location germanywestcentral \
            --admin-user  ${{ secrets.DB_USER }}\
            --admin-password ${{ secrets.DB_PASS }} \
            --sku-name B_Gen5_1

      - name: Create PostgreSQL Database
        run: |
          az postgres db create \
            --resource-group dev-rg \
            --server-name selfimprovementaipsql \
            --name ${{ DB_NAME }}