name: 💣 Destroy Infrastructure with Terraform on Azure
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy-infra:
    runs-on: ubuntu-latest

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      # - name: Generate SSH Key
      #   run: |
      #     mkdir -p .ssh
      #     ssh-keygen -t rsa -b 4096 -N "$SSH_PASSWORD" -C "$SSH_USER" -q -f .ssh/id_rsa
      #     sshKey=$(cat .ssh/id_rsa.pub)
      #     echo "arm_ssh_key=\"$sshKey\"" > ./terraform/terraform.tfvars

      # - name: Generate .tfvars file
      #   run: |
      #     echo "arm_subscription_id = \"$ARM_SUBSCRIPTION_ID\"" >> ./terraform/terraform.tfvars
      #     echo "arm_tenant_id       = \"$ARM_TENANT_ID\""       >> ./terraform/terraform.tfvars
      #     echo "arm_client_id       = \"$ARM_CLIENT_ID\""       >> ./terraform/terraform.tfvars
      #     echo "arm_client_secret   = \"$ARM_CLIENT_SECRET\""   >> ./terraform/terraform.tfvars
      #     cat ./terraform/terraform.tfvars

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
