name: Run Azure Login with OIDC and Deploy Infrastructure with Terraform
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Change to Terraform directory
        run: cd terraform/

      - name: Generate SSH Key
        run: |
          mkdir -p .ssh
          sshPassword="${{ secrets.SSH_PASSWORD }}"
          sshUser="${{ secrets.SSH_USER }}"
          ssh-keygen -t rsa -b 4096 -N "$sshPassword" -C "$sshUser" -q -f .ssh/id_rsa
          sshKey=$(cat .ssh/id_rsa.pub)
          echo "arm_ssh_key=\"$sshKey\"" >> terraform.tfvars

      - name: Generate .tfvars file
        run: |
          echo "arm_subscription_id = \"${{ secrets.ARM_SUBSCRIPTION_ID }}\"" > terraform.tfvars
          echo "arm_tenant_id       = \"${{ secrets.ARM_TENANT_ID }}\""       >> terraform.tfvars
          echo "arm_client_id       = \"${{ secrets.ARM_CLIENT_ID }}\""       >> terraform.tfvars
          echo "arm_client_secret   = \"${{ secrets.ARM_CLIENT_SECRET }}\""   >> terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=main.tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve main.tfplan
